loki:
   auth_enabled: false
   schemaConfig:
     configs:
       - from: "2024-04-01"
         store: tsdb
         object_store: s3
         schema: v13
         index:
           prefix: loki_index_
           period: 24h
   storage_config:
     aws:
       region: <AWS_REGION>
       bucketnames: <AWS_BUCKET_NAME_FOR_CHUNKS>      
       s3forcepathstyle: false
   ingester:
       chunk_encoding: snappy
       
   pattern_ingester:
       enabled: true

   limits_config:
     allow_structured_metadata: true
     volume_enabled: true
     retention_period: 672h # 28 days retention
   
   querier:
      max_concurrent: 4


   # The region of the buckets and the cluster should be the same
   storage:
      type: s3
      bucketNames:
        chunks: <AWS_BUCKET_NAME_FOR_CHUNKS>  
        ruler: <AWS_BUCKET_NAME_FOR_RULER> # It's not going to be used but needs to be declared 
        # admin: "<Insert s3 bucket name>" # Your actual S3 bucket name (loki-aws-dev-admin) - GEL customers only
      s3:
        region: <AWS_REGION> 

   ruler:
    enabled: false
    storage:
      type: s3  
      s3:
        region: <AWS_REGION> 
        bucketnames:
          - <AWS_BUCKET_NAME_FOR_RULER> 

   
   compactor:
     retention_enabled: true 
     delete_request_store: s3
   


serviceAccount:
 create: true
 annotations:
   "eks.amazonaws.com/role-arn": "arn:aws:iam::<AWS_ACCOUNT_ID>:role/LokiServiceAccountRole" 

deploymentMode: SimpleScalable


# This exposes the Loki gateway so it can be written to and queried externaly
gateway:
 service:
   type: LoadBalancer
 basicAuth: 
     enabled: false
#     existingSecret: loki-basic-auth


backend:
  replicas: 2
#  resources: {}
#  nodeSelector: {}
  persistence:
    volumeClaimsEnabled: true
    size: 10Gi
    storageClass: gp2
read:
  replicas: 2
#  resources: {}
#  nodeSelector: {}
  persistence:
    volumeClaimsEnabled: true
    size: 10Gi
    storageClass: gp2  
write:
  replicas: 2 # To ensure data durability with replication
#  resources: {}
#  nodeSelector: {}
  persistence:
    volumeClaimsEnabled: true
    size: 10Gi
    storageClass: gp2



singleBinary:
 replicas: 0

test:
  enabled: false

lokiCanary:
  enabled: false

minio:
 enabled: false
memcachedExporter:
  enabled: false
resultsCache:
  enabled: false
chunksCache:
  enabled: false